/* =========================================================================
 * EDL — references.js (AUTO-GERADO)
 *
 * Este arquivo é gerado automaticamente a partir de references.bib via
 * scripts/bib2json.py. NÃO EDITE MANUALMENTE.
 *
 * Propósito: expor a bibliografia como `window.EDL.data.references`
 * para consumo pelo app em runtime. Usamos <script> em vez de fetch()
 * de references.json porque o Safari bloqueia fetch de arquivos locais
 * em protocolo file:// — o que quebraria o app ao ser aberto por duplo-
 * clique no index.html.
 *
 * O arquivo references.json (gerado em paralelo) serve para download
 * pelo usuário e para importação em gerenciadores como Zotero, EndNote,
 * Mendeley, Pandoc etc. Ambos derivam da mesma fonte.
 * ========================================================================= */

window.EDL = window.EDL || {};
window.EDL.data = window.EDL.data || {};
window.EDL.data.references = {
  "_generated_from": "references.bib",
  "_generated_by": "scripts/bib2json.py",
  "_generated_at_utc": "2026-06-06T17:19:38Z",
  "_warning": "DO NOT EDIT THIS FILE MANUALLY. It is derived from references.bib — regenerate via scripts/bib2json.py.",
  "items": [
    {
      "id": "graunt1662",
      "type": "book",
      "author": [
        {
          "family": "Graunt",
          "given": "John"
        }
      ],
      "issued": {
        "date-parts": [
          [
            1662
          ]
        ]
      },
      "title": "Natural and Political Observations Made upon the Bills of Mortality",
      "publisher": "Thomas Roycroft",
      "publisher-place": "London",
      "note": "Marco fundador da análise estatística de dados populacionais de mortalidade; considerado um dos textos seminais da demografia e, em última instância, da epidemiologia.",
      "custom": {
        "module": [
          1
        ]
      }
    },
    {
      "id": "langmuir1976farr",
      "type": "article-journal",
      "author": [
        {
          "family": "Langmuir",
          "given": "Alexander D."
        }
      ],
      "issued": {
        "date-parts": [
          [
            1976
          ]
        ]
      },
      "title": "William Farr: founder of modern concepts of surveillance",
      "container-title": "International Journal of Epidemiology",
      "volume": "5",
      "issue": "1",
      "page": "13–18",
      "DOI": "10.1093/ije/5.1.13",
      "note": "Retrato do papel de William Farr na sistematização das estatísticas de mortalidade britânicas e na construção da vigilância epidemiológica moderna.",
      "custom": {
        "module": [
          1
        ]
      }
    },
    {
      "id": "moriyama1993classification",
      "type": "book",
      "author": [
        {
          "family": "Moriyama",
          "given": "Iwao Milton"
        }
      ],
      "issued": {
        "date-parts": [
          [
            1993
          ]
        ]
      },
      "title": "Historical development of cause of death statistics",
      "publisher": "Indiana University, Population Institute for Research and Training",
      "note": "Compilação histórica das conferências internacionais de estatística (Bruxelas 1853, Paris 1855, Viena 1891, Chicago 1893) que culminaram na Classificação Internacional de Doenças.",
      "custom": {
        "module": [
          1
        ]
      }
    },
    {
      "id": "doll1954smoking",
      "type": "article-journal",
      "author": [
        {
          "family": "Doll",
          "given": "Richard"
        },
        {
          "family": "Hill",
          "given": "Austin Bradford"
        }
      ],
      "issued": {
        "date-parts": [
          [
            1954
          ]
        ]
      },
      "title": "The mortality of doctors in relation to their smoking habits: a preliminary report",
      "container-title": "British Medical Journal",
      "volume": "1",
      "issue": "4877",
      "page": "1451–1455",
      "DOI": "10.1136/bmj.1.4877.1451",
      "note": "Primeiro relato do clássico estudo de coorte dos médicos britânicos, demonstrando associação entre tabagismo e câncer de pulmão — marco inaugural da epidemiologia moderna de doenças crônicas.",
      "custom": {
        "module": [
          1
        ]
      }
    },
    {
      "id": "hill1965criteria",
      "type": "article-journal",
      "author": [
        {
          "family": "Hill",
          "given": "Austin Bradford"
        }
      ],
      "issued": {
        "date-parts": [
          [
            1965
          ]
        ]
      },
      "title": "The Environment and Disease: Association or Causation?",
      "container-title": "Proceedings of the Royal Society of Medicine",
      "volume": "58",
      "issue": "5",
      "page": "295–300",
      "DOI": "10.1177/003591576505800503",
      "note": "Formulação dos nove critérios de causalidade que ainda hoje orientam a inferência causal a partir de associações estatísticas em epidemiologia.",
      "custom": {
        "module": [
          1
        ]
      }
    },
    {
      "id": "hippocrates_airs_waters",
      "type": "chapter",
      "author": [
        {
          "literal": "Hippocrates"
        }
      ],
      "editor": [
        {
          "family": "Jones",
          "given": "W. H. S."
        }
      ],
      "issued": {
        "date-parts": [
          [
            1923
          ]
        ]
      },
      "title": "Airs, Waters, Places",
      "container-title": "Hippocrates, Volume I",
      "publisher": "Harvard University Press",
      "publisher-place": "Cambridge, MA",
      "ISBN": "978-0674991620",
      "note": "Tratado hipocrático do séc. V a.C. (escrito em grego antigo) na edição bilíngue grego-inglês de W.H.S. Jones — referência canônica internacional. Considerado precursor da epidemiologia ambiental ao relacionar doença, clima, águas, ventos, estações do ano e modo de vida das populações.",
      "custom": {
        "module": [
          1
        ]
      }
    },
    {
      "id": "jenner1798inquiry",
      "type": "book",
      "author": [
        {
          "family": "Jenner",
          "given": "Edward"
        }
      ],
      "issued": {
        "date-parts": [
          [
            1798
          ]
        ]
      },
      "title": "An Inquiry into the Causes and Effects of the Variolae Vaccinae, a Disease Discovered in Some of the Western Counties of England, Particularly Gloucestershire, and Known by the Name of the Cow Pox",
      "publisher": "Sampson Low",
      "publisher-place": "London",
      "note": "Tratado fundador da vacinação contra a varíola; primeira documentação sistemática do uso da varíola bovina (cowpox) para proteger humanos da varíola humana — marco da prevenção primária baseada em evidência empírica.",
      "custom": {
        "module": [
          1
        ]
      }
    },
    {
      "id": "louis1835saignee",
      "type": "book",
      "author": [
        {
          "family": "Louis",
          "given": "Pierre Charles Alexandre"
        }
      ],
      "issued": {
        "date-parts": [
          [
            1835
          ]
        ]
      },
      "title": "Recherches sur les effets de la saignée dans quelques maladies inflammatoires et sur l'action de l'émétique et des vésicatoires dans la pneumonie",
      "publisher": "J.-B. Baillière",
      "publisher-place": "Paris",
      "note": "Aplicação pioneira do \"método numérico\" — Louis defende que a avaliação de tratamentos médicos deve se apoiar na contagem sistemática e comparação de grupos, não na impressão clínica individual. Antecipa a lógica do ensaio clínico controlado.",
      "custom": {
        "module": [
          1
        ]
      }
    },
    {
      "id": "semmelweis1861aetiologie",
      "type": "book",
      "author": [
        {
          "family": "Semmelweis",
          "given": "Ignaz"
        }
      ],
      "issued": {
        "date-parts": [
          [
            1861
          ]
        ]
      },
      "title": "Die Aetiologie, der Begriff und die Prophylaxis des Kindbettfiebers",
      "publisher": "C. A. Hartleben's Verlags-Expedition",
      "publisher-place": "Pest, Wien und Leipzig",
      "note": "Monografia em que Semmelweis sistematiza suas observações de 1847 no Hospital Geral de Viena, demonstrando que a antissepsia com solução clorada reduz drasticamente a mortalidade por febre puerperal. Marco da prevenção baseada em comparação entre grupos, antes mesmo da teoria germinal.",
      "custom": {
        "module": [
          1
        ]
      }
    },
    {
      "id": "koch1884aetiologie",
      "type": "article-journal",
      "author": [
        {
          "family": "Koch",
          "given": "Robert"
        }
      ],
      "issued": {
        "date-parts": [
          [
            1884
          ]
        ]
      },
      "title": "Die Aetiologie der Tuberkulose",
      "container-title": "Mittheilungen aus dem Kaiserlichen Gesundheitsamte",
      "volume": "2",
      "page": "1–88",
      "note": "Monografia expandida em que Koch consolida a descoberta do bacilo da tuberculose (anunciada em 1882) e formula os critérios — depois conhecidos como \"postulados de Koch\" — para atribuir uma doença a um agente microbiano específico.",
      "custom": {
        "module": [
          1
        ]
      }
    },
    {
      "id": "chagas1909nova",
      "type": "article-journal",
      "author": [
        {
          "family": "Chagas",
          "given": "Carlos"
        }
      ],
      "issued": {
        "date-parts": [
          [
            1909
          ]
        ]
      },
      "title": "Nova tripanozomiaze humana: Estudos sobre a morfolojia e o ciclo evolutivo do Schizotrypanum cruzi n. gen., n. sp., ajente etiolojico de nova entidade morbida do homem",
      "container-title": "Memórias do Instituto Oswaldo Cruz",
      "volume": "1",
      "issue": "2",
      "page": "159–218",
      "DOI": "10.1590/S0074-02761909000200008",
      "note": "Paper canônico em que Carlos Chagas descreve simultaneamente o agente etiológico (Trypanosoma cruzi), o vetor (barbeiro), o ciclo biológico e o quadro clínico da doença que hoje leva seu nome — feito sem precedentes na história da medicina.",
      "custom": {
        "module": [
          1
        ]
      }
    },
    {
      "id": "mrc1948streptomycin",
      "type": "article-journal",
      "author": [
        {
          "literal": "Medical Research Council"
        }
      ],
      "issued": {
        "date-parts": [
          [
            1948
          ]
        ]
      },
      "title": "Streptomycin Treatment of Pulmonary Tuberculosis: A Medical Research Council Investigation",
      "container-title": "British Medical Journal",
      "volume": "2",
      "issue": "4582",
      "page": "769–782",
      "DOI": "10.1136/bmj.2.4582.769",
      "note": "Frequentemente considerado o primeiro ensaio clínico randomizado moderno. Incorporou randomização (por envelopes selados), comparação controlada (estreptomicina vs. repouso) e cegamento parcial — um modelo metodológico que se tornaria o padrão-ouro da avaliação de intervenções.",
      "custom": {
        "module": [
          1
        ]
      }
    },
    {
      "id": "dawber1951framingham",
      "type": "article-journal",
      "author": [
        {
          "family": "Dawber",
          "given": "Thomas R."
        },
        {
          "family": "Meadors",
          "given": "Gilcin F."
        },
        {
          "family": "Moore",
          "given": "Felix E."
        }
      ],
      "issued": {
        "date-parts": [
          [
            1951
          ]
        ]
      },
      "title": "Epidemiological Approaches to Heart Disease: The Framingham Study",
      "container-title": "American Journal of Public Health and the Nation's Health",
      "volume": "41",
      "issue": "3",
      "page": "279–286",
      "DOI": "10.2105/AJPH.41.3.279",
      "note": "Primeiro paper a descrever o desenho metodológico do Framingham Heart Study, coorte longitudinal iniciada em 1948 em Massachusetts que viria a estabelecer o conceito moderno de \"fator de risco\" cardiovascular (hipertensão, colesterol, tabagismo, diabetes).",
      "custom": {
        "module": [
          1
        ]
      }
    },
    {
      "id": "doll1950smoking",
      "type": "article-journal",
      "author": [
        {
          "family": "Doll",
          "given": "Richard"
        },
        {
          "family": "Hill",
          "given": "A. Bradford"
        }
      ],
      "issued": {
        "date-parts": [
          [
            1950
          ]
        ]
      },
      "title": "Smoking and Carcinoma of the Lung: Preliminary Report",
      "container-title": "British Medical Journal",
      "volume": "2",
      "issue": "4682",
      "page": "739–748",
      "DOI": "10.1136/bmj.2.4682.739",
      "note": "Estudo caso-controle pioneiro que demonstrou forte associação entre tabagismo e câncer de pulmão. Antecede o estudo de coorte dos médicos britânicos (Doll \\& Hill 1954) e é um dos primeiros usos clássicos do desenho caso-controle para doenças crônicas.",
      "custom": {
        "module": [
          1
        ]
      }
    },
    {
      "id": "stepan1976beginnings",
      "type": "book",
      "author": [
        {
          "family": "Stepan",
          "given": "Nancy Leys"
        }
      ],
      "issued": {
        "date-parts": [
          [
            1976
          ]
        ]
      },
      "title": "Beginnings of Brazilian Science: Oswaldo Cruz, Medical Research, and Policy, 1890–1920",
      "publisher": "Science History Publications",
      "publisher-place": "New York",
      "ISBN": "978-0882020389",
      "note": "Estudo acadêmico de referência sobre Oswaldo Cruz, o sanitarismo brasileiro do início do século XX e a institucionalização da pesquisa biomédica no Brasil.",
      "custom": {
        "module": [
          1
        ]
      }
    },
    {
      "id": "ebmworkinggroup1992evidence",
      "type": "article-journal",
      "author": [
        {
          "literal": "Evidence-Based Medicine Working Group"
        }
      ],
      "issued": {
        "date-parts": [
          [
            1992
          ]
        ]
      },
      "title": "Evidence-Based Medicine: A New Approach to Teaching the Practice of Medicine",
      "container-title": "JAMA",
      "volume": "268",
      "issue": "17",
      "page": "2420–2425",
      "DOI": "10.1001/jama.1992.03490170092032",
      "note": "Paper coletivo do grupo de McMaster (Guyatt, Sackett e outros) que introduz formalmente o termo \"Evidence-Based Medicine\" e propõe sua sistematização como abordagem para ensino e prática médica.",
      "custom": {
        "module": [
          1
        ]
      }
    },
    {
      "id": "chalmers1993cochrane",
      "type": "article-journal",
      "author": [
        {
          "family": "Chalmers",
          "given": "Iain"
        }
      ],
      "issued": {
        "date-parts": [
          [
            1993
          ]
        ]
      },
      "title": "The Cochrane Collaboration: Preparing, Maintaining, and Disseminating Systematic Reviews of the Effects of Health Care",
      "container-title": "Annals of the New York Academy of Sciences",
      "volume": "703",
      "issue": "1",
      "page": "156–165",
      "DOI": "10.1111/j.1749-6632.1993.tb26345.x",
      "note": "Paper inaugural da Cochrane Collaboration — define a missão e estrutura da organização internacional dedicada a preparar, manter e disseminar revisões sistemáticas dos efeitos de intervenções em saúde.",
      "custom": {
        "module": [
          1
        ]
      }
    },
    {
      "id": "geison1995pasteur",
      "type": "book",
      "author": [
        {
          "family": "Geison",
          "given": "Gerald L."
        }
      ],
      "issued": {
        "date-parts": [
          [
            1995
          ]
        ]
      },
      "title": "The Private Science of Louis Pasteur",
      "publisher": "Princeton University Press",
      "publisher-place": "Princeton, NJ",
      "ISBN": "978-0691015521",
      "note": "Biografia acadêmica de referência sobre Pasteur, baseada em seus cadernos de laboratório. Documenta a consolidação da teoria germinal das doenças e o papel de Pasteur na transformação da medicina e da saúde pública na segunda metade do séc. XIX.",
      "custom": {
        "module": [
          1
        ]
      }
    },
    {
      "id": "murray1996gbd",
      "type": "book",
      "editor": [
        {
          "family": "Murray",
          "given": "Christopher J. L."
        },
        {
          "family": "Lopez",
          "given": "Alan D."
        }
      ],
      "issued": {
        "date-parts": [
          [
            1996
          ]
        ]
      },
      "title": "The Global Burden of Disease: A Comprehensive Assessment of Mortality and Disability from Diseases, Injuries, and Risk Factors in 1990 and Projected to 2020",
      "publisher": "Harvard University Press",
      "publisher-place": "Cambridge, MA",
      "ISBN": "978-0674354487",
      "note": "Marco inaugural do projeto Global Burden of Disease (GBD), em colaboração com a OMS e o Banco Mundial. Introduz medidas como DALY (anos de vida ajustados por incapacidade) e estabelece a linguagem da carga de doença global para planejamento em saúde pública.",
      "custom": {
        "module": [
          1
        ]
      }
    },
    {
      "id": "tognotti2013quarantine",
      "type": "article-journal",
      "author": [
        {
          "family": "Tognotti",
          "given": "Eugenia"
        }
      ],
      "issued": {
        "date-parts": [
          [
            2013
          ]
        ]
      },
      "title": "Lessons from the History of Quarantine, from Plague to Influenza A",
      "container-title": "Emerging Infectious Diseases",
      "volume": "19",
      "issue": "2",
      "page": "254–259",
      "DOI": "10.3201/eid1902.120312",
      "note": "Revisão histórica das práticas de quarentena e cordão sanitário desde a Idade Média (peste bubônica em Ragusa, 1377) até epidemias modernas — documenta a emergência da resposta coletiva e estatal a surtos epidêmicos.",
      "custom": {
        "module": [
          1
        ]
      }
    },
    {
      "id": "hernan2020causal",
      "type": "book",
      "author": [
        {
          "family": "Hernán",
          "given": "Miguel A."
        },
        {
          "family": "Robins",
          "given": "James M."
        }
      ],
      "issued": {
        "date-parts": [
          [
            2020
          ]
        ]
      },
      "title": "Causal Inference: What If",
      "publisher": "Chapman \\& Hall/CRC",
      "publisher-place": "Boca Raton, FL",
      "URL": "https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/",
      "ISBN": "978-1420076165",
      "note": "Texto-referência da inferência causal contemporânea em epidemiologia. Sistematiza diagramas acíclicos direcionados (DAGs), modelos contrafactuais, emulação de ensaios-alvo (target trial emulation) e análise crítica de vieses em estudos observacionais. Versão atualizada disponível gratuitamente online.",
      "custom": {
        "module": [
          1
        ]
      }
    },
    {
      "id": "jamoulle1986information",
      "type": "chapter",
      "author": [
        {
          "family": "Jamoulle",
          "given": "Marc"
        }
      ],
      "editor": [
        {
          "family": "Berleur",
          "given": "Jacques"
        },
        {
          "family": "Labet-Maris",
          "given": "Claire"
        },
        {
          "family": "Poswick",
          "given": "Robert F."
        },
        {
          "family": "Valenduc",
          "given": "G\\'erard"
        },
        {
          "family": "Van Bastelaer",
          "given": "Philippe"
        }
      ],
      "issued": {
        "date-parts": [
          [
            1986
          ]
        ]
      },
      "title": "Information et informatisation en m\\'edecine g\\'en\\'erale",
      "container-title": "Les informa-g-iciens",
      "publisher": "Presses Universitaires de Namur",
      "publisher-place": "Namur",
      "page": "193–209",
      "note": "Texto seminal em que Marc Jamoulle propõe pela primeira vez o conceito de prevenção quaternária, no contexto da informatização da medicina geral.",
      "custom": {
        "module": [
          1
        ]
      }
    },
    {
      "id": "jamoulle2015answer",
      "type": "article-journal",
      "author": [
        {
          "family": "Jamoulle",
          "given": "Marc"
        }
      ],
      "issued": {
        "date-parts": [
          [
            2015
          ]
        ]
      },
      "title": "Quaternary Prevention, an Answer of Family Doctors to Overmedicalization",
      "container-title": "International Journal of Health Policy and Management",
      "volume": "4",
      "issue": "2",
      "page": "61–64",
      "DOI": "10.15171/ijhpm.2015.24",
      "note": "Formulação madura do conceito como resposta dos médicos de família à supermedicalização: define prevenção quaternária como a proteção do paciente contra invasões médicas desnecessárias.",
      "custom": {
        "module": [
          1
        ]
      }
    },
    {
      "id": "martins2018quaternary",
      "type": "article-journal",
      "author": [
        {
          "family": "Martins",
          "given": "Carlos"
        },
        {
          "family": "Godycki-Cwirko",
          "given": "Maciej"
        },
        {
          "family": "Heleno",
          "given": "Bruno"
        },
        {
          "family": "Brodersen",
          "given": "John"
        }
      ],
      "issued": {
        "date-parts": [
          [
            2018
          ]
        ]
      },
      "title": "Quaternary Prevention: Reviewing the Concept",
      "container-title": "European Journal of General Practice",
      "volume": "24",
      "issue": "1",
      "page": "106–111",
      "DOI": "10.1080/13814788.2017.1422177",
      "note": "Revisão crítica do conceito de prevenção quaternária e de suas aplicações na prática clínica contemporânea, especialmente no contexto de rastreamentos e tratamentos com balanço incerto entre benefício e dano.",
      "custom": {
        "module": [
          1
        ]
      }
    },
    {
      "id": "cdc2012principles",
      "type": "report",
      "author": [
        {
          "literal": "Centers for Disease Control and Prevention"
        }
      ],
      "issued": {
        "date-parts": [
          [
            2012
          ]
        ]
      },
      "title": "Principles of Epidemiology in Public Health Practice",
      "publisher-place": "Atlanta, GA",
      "edition": "3rd",
      "URL": "https://www.cdc.gov/training-publichealth101/php/training/introduction-to-epidemiology.html",
      "note": "Referência introdutória de domínio público amplamente adotada em cursos de Medicina e Saúde Pública. Conceitos de endemia/surto/epidemia/pandemia, reservatório, cadeia epidemiológica e caso notificado/confirmado. O conteúdo detalhado sobre cadeia de transmissão (elos, portais de saída/entrada, modos de transmissão e hospedeiro suscetível) está na Lesson 1, Section 10 do curso, arquivada em https://archive.cdc.gov/www_cdc_gov/csels/dsepd/ss1978/lesson1/section10.html",
      "custom": {
        "module": [
          2,
          3
        ]
      }
    },
    {
      "id": "cdc_niosh_chain2024",
      "type": "webpage",
      "author": [
        {
          "literal": "Centers for Disease Control and Prevention / National Institute for Occupational Safety and Health"
        }
      ],
      "issued": {
        "date-parts": [
          [
            2024
          ]
        ]
      },
      "title": "Chain of Infection",
      "URL": "https://www.cdc.gov/niosh/learning/safetyculturehc/module-2/3.html",
      "note": "Definição e descrição dos seis elos da cadeia de infecção: agente patogênico, reservatório/fonte, portal de saída, modo de transmissão, portal de entrada e hospedeiro suscetível. Recurso CDC/NIOSH de referência direta para o conteúdo dos elos apresentados no Módulo 3. — NIOSH Safety Culture in Healthcare, Module 2, Section 3",
      "custom": {
        "module": [
          3
        ]
      }
    },
    {
      "id": "nishiura2007incubation",
      "type": "article-journal",
      "author": [
        {
          "family": "Nishiura",
          "given": "Hiroshi"
        }
      ],
      "issued": {
        "date-parts": [
          [
            2007
          ]
        ]
      },
      "title": "Early efforts in modeling the incubation period of infectious diseases with an acute course of illness",
      "container-title": "Emerging Themes in Epidemiology",
      "volume": "4",
      "issue": "2",
      "DOI": "10.1186/1742-7622-4-2",
      "note": "Revisão histórica dos primeiros esforços de modelagem do período de incubação, começando com os estudos de 1919 sobre a gripe espanhola em navios.",
      "custom": {
        "module": [
          4
        ]
      }
    },
    {
      "id": "azman2013cholera",
      "type": "article-journal",
      "author": [
        {
          "family": "Azman",
          "given": "Andrew S."
        },
        {
          "family": "Rudolph",
          "given": "Kara E."
        },
        {
          "family": "Cummings",
          "given": "Derek A. T."
        },
        {
          "family": "Lessler",
          "given": "Justin"
        }
      ],
      "issued": {
        "date-parts": [
          [
            2013
          ]
        ]
      },
      "title": "The incubation period of cholera: A systematic review",
      "container-title": "Journal of Infection",
      "volume": "66",
      "issue": "5",
      "page": "432–438",
      "DOI": "10.1016/j.jinf.2012.11.013",
      "note": "Revisão sistemática do período de incubação da cólera, estabelecendo a faixa de 12 horas a 5 dias usada no comparador visual do Módulo 4.",
      "custom": {
        "module": [
          4,
          8
        ]
      }
    },
    {
      "id": "li2020covid",
      "type": "article-journal",
      "author": [
        {
          "family": "Li",
          "given": "Qun"
        },
        {
          "family": "Guan",
          "given": "Xuhua"
        },
        {
          "family": "Wu",
          "given": "Peng"
        },
        {
          "family": "Wang",
          "given": "Xiaoye"
        },
        {
          "family": "Zhou",
          "given": "Lei"
        },
        {
          "family": "Tong",
          "given": "Yeqing"
        },
        {
          "literal": "others"
        }
      ],
      "issued": {
        "date-parts": [
          [
            2020
          ]
        ]
      },
      "title": "Early Transmission Dynamics in Wuhan, China, of Novel Coronavirus-Infected Pneumonia",
      "container-title": "New England Journal of Medicine",
      "volume": "382",
      "issue": "13",
      "page": "1199–1207",
      "DOI": "10.1056/NEJMoa2001316",
      "note": "Primeira caracterização epidemiológica rigorosa do SARS-CoV-2 em Wuhan. Incubação mediana de 5,2 dias (percentil 95 de 12,5 dias) — base do período de quarentena de 14 dias inicialmente adotado globalmente. Citado no Módulo 1 como marco da pandemia de 2020-2023.",
      "custom": {
        "module": [
          1,
          4
        ]
      }
    },
    {
      "id": "traylen2011reactivation",
      "type": "article-journal",
      "author": [
        {
          "family": "Traylen",
          "given": "Christopher M."
        },
        {
          "family": "Patel",
          "given": "Hersh R."
        },
        {
          "family": "Fondaw",
          "given": "Wylder"
        },
        {
          "family": "Mahatme",
          "given": "Sheran"
        },
        {
          "family": "Williams",
          "given": "John F."
        },
        {
          "family": "Walker",
          "given": "Lia R."
        },
        {
          "family": "Dyson",
          "given": "Ossie F."
        },
        {
          "family": "Arce",
          "given": "Sergio"
        },
        {
          "family": "Akula",
          "given": "Shaw M."
        }
      ],
      "issued": {
        "date-parts": [
          [
            2011
          ]
        ]
      },
      "title": "Virus reactivation: a panoramic view in human infections",
      "container-title": "Future Virology",
      "volume": "6",
      "issue": "4",
      "page": "451–463",
      "DOI": "10.2217/fvl.11.21",
      "note": "Panorama geral sobre latência e reativação viral, com foco especial nos herpesvírus — base conceitual para a distinção entre incubação e latência no Módulo 4.",
      "custom": {
        "module": [
          4
        ]
      }
    },
    {
      "id": "kermack1927sir",
      "type": "article-journal",
      "author": [
        {
          "family": "Kermack",
          "given": "William Ogilvy"
        },
        {
          "family": "McKendrick",
          "given": "Anderson Gray"
        }
      ],
      "issued": {
        "date-parts": [
          [
            1927
          ]
        ]
      },
      "title": "A Contribution to the Mathematical Theory of Epidemics",
      "container-title": "Proceedings of the Royal Society A",
      "volume": "115",
      "issue": "772",
      "page": "700–721",
      "DOI": "10.1098/rspa.1927.0118",
      "note": "Artigo fundador do modelo SIR. Introduziu a formalização matemática da dinâmica epidêmica em compartimentos suscetível/infectado/recuperado.",
      "custom": {
        "module": [
          7
        ]
      }
    },
    {
      "id": "anderson1991infectious",
      "type": "book",
      "author": [
        {
          "family": "Anderson",
          "given": "Roy M."
        },
        {
          "family": "May",
          "given": "Robert M."
        }
      ],
      "issued": {
        "date-parts": [
          [
            1991
          ]
        ]
      },
      "title": "Infectious Diseases of Humans: Dynamics and Control",
      "publisher": "Oxford University Press",
      "publisher-place": "Oxford",
      "ISBN": "978-0198540403",
      "note": "Texto-referência da epidemiologia matemática moderna. Fonte canônica para R₀, limiar de imunidade de rebanho e modelos compartimentais.",
      "custom": {
        "module": [
          5,
          6,
          7
        ]
      }
    },
    {
      "id": "snow1855cholera",
      "type": "book",
      "author": [
        {
          "family": "Snow",
          "given": "John"
        }
      ],
      "issued": {
        "date-parts": [
          [
            1855
          ]
        ]
      },
      "title": "On the Mode of Communication of Cholera",
      "publisher": "John Churchill",
      "publisher-place": "London",
      "edition": "2nd",
      "note": "Fonte primária. Segunda edição da monografia de Snow, incluindo o \"Grand Experiment\" (comparação Southwark \\& Vauxhall × Lambeth) — uma das primeiras análises quase-experimentais da história da medicina.",
      "custom": {
        "module": [
          8
        ]
      }
    },
    {
      "id": "johnson2006ghostmap",
      "type": "book",
      "author": [
        {
          "family": "Johnson",
          "given": "Steven"
        }
      ],
      "issued": {
        "date-parts": [
          [
            2006
          ]
        ]
      },
      "title": "The Ghost Map: The Story of London's Most Terrifying Epidemic—and How It Changed Science, Cities, and the Modern World",
      "publisher": "Riverhead Books",
      "publisher-place": "New York",
      "ISBN": "978-1594489259",
      "note": "Reconstrução narrativa popular do surto de Soho 1854, combinando pesquisa histórica com contexto social e urbano.",
      "custom": {
        "module": [
          8
        ]
      }
    },
    {
      "id": "ali2015cholera",
      "type": "article-journal",
      "author": [
        {
          "family": "Ali",
          "given": "Mohammad"
        },
        {
          "family": "Nelson",
          "given": "Allyson R."
        },
        {
          "family": "Lopez",
          "given": "Anna Lena"
        },
        {
          "family": "Sack",
          "given": "David A."
        }
      ],
      "issued": {
        "date-parts": [
          [
            2015
          ]
        ]
      },
      "title": "Updated Global Burden of Cholera in Endemic Countries",
      "container-title": "PLOS Neglected Tropical Diseases",
      "volume": "9",
      "issue": "6",
      "page": "e0003832",
      "DOI": "10.1371/journal.pntd.0003832",
      "note": "Atualização global da carga de cólera em países endêmicos, com estimativas de casos e mortes anuais.",
      "custom": {
        "module": [
          8
        ]
      }
    },
    {
      "id": "orata2014haiti",
      "type": "article-journal",
      "author": [
        {
          "family": "Orata",
          "given": "Fabini D."
        },
        {
          "family": "Keim",
          "given": "Paul S."
        },
        {
          "family": "Boucher",
          "given": "Yan"
        }
      ],
      "issued": {
        "date-parts": [
          [
            2014
          ]
        ]
      },
      "title": "The 2010 Cholera Outbreak in Haiti: How Science Solved a Controversy",
      "container-title": "PLOS Pathogens",
      "volume": "10",
      "issue": "4",
      "page": "e1003967",
      "DOI": "10.1371/journal.ppat.1003967",
      "note": "Revisão da análise genômica que confirmou a origem nepalesa do surto de cólera no Haiti, encerrando a controvérsia sobre a responsabilidade da MINUSTAH.",
      "custom": {
        "module": [
          8
        ]
      }
    },
    {
      "id": "li2018cholera",
      "type": "article-journal",
      "author": [
        {
          "family": "Li",
          "given": "Peter"
        }
      ],
      "issued": {
        "date-parts": [
          [
            2018
          ]
        ]
      },
      "title": "cholera: Amend, Augment and Aid Analysis of John Snow's Cholera Map",
      "container-title": "Journal of Open Source Software",
      "volume": "3",
      "issue": "23",
      "page": "596",
      "DOI": "10.21105/joss.00596",
      "note": "Pacote R que moderniza a análise de Snow com dados digitalizados, algoritmos de caminhada em grafo, e ferramentas de Voronoi. Fonte dos dados usados no mapa interativo do Módulo 8.",
      "custom": {
        "module": [
          8
        ]
      }
    },
    {
      "id": "dodson1992snow",
      "type": "article-journal",
      "author": [
        {
          "family": "Dodson",
          "given": "Rusty"
        },
        {
          "family": "Tobler",
          "given": "Waldo"
        }
      ],
      "issued": {
        "date-parts": [
          [
            1992
          ]
        ]
      },
      "title": "The Snow map digitized",
      "container-title": "National Center for Geographic Information and Analysis, UCSB",
      "note": "Digitalização original das coordenadas de mortes, bombas e ruas do mapa de John Snow (1855). Base dos datasets hoje preservados no pacote R cholera.",
      "custom": {
        "module": [
          8
        ]
      }
    },
    {
      "id": "mspp2016haiti",
      "type": "webpage",
      "author": [
        {
          "literal": "Ministère de la Santé Publique et de la Population du Haïti"
        }
      ],
      "issued": {
        "date-parts": [
          [
            2010
          ]
        ]
      },
      "title": "Rapports mensuels sur l'épidémie de choléra",
      "note": "Dados mensais de casos e mortes reportados pelo MSPP Haiti, usados no gráfico temporal do Módulo 8. — Série temporal oficial mensal do surto de cólera no Haiti, out/2010 a mar/2016 (66 observações).",
      "custom": {
        "module": [
          8
        ]
      }
    },
    {
      "id": "piarroux2011haiti",
      "type": "article-journal",
      "author": [
        {
          "family": "Piarroux",
          "given": "Renaud"
        },
        {
          "family": "Barrais",
          "given": "Robert"
        },
        {
          "family": "Faucher",
          "given": "Benoît"
        },
        {
          "family": "Haus",
          "given": "Rachel"
        },
        {
          "family": "Piarroux",
          "given": "Martine"
        },
        {
          "family": "Gaudart",
          "given": "Jean"
        },
        {
          "family": "Magloire",
          "given": "Roc"
        },
        {
          "family": "Raoult",
          "given": "Didier"
        }
      ],
      "issued": {
        "date-parts": [
          [
            2011
          ]
        ]
      },
      "title": "Understanding the Cholera Epidemic, Haiti",
      "container-title": "Emerging Infectious Diseases",
      "volume": "17",
      "issue": "7",
      "page": "1161–1168",
      "DOI": "10.3201/eid1707.110059",
      "note": "Primeiro estudo epidemiológico a atribuir formalmente a origem do surto ao acampamento da MINUSTAH em Meille, antes mesmo da confirmação genômica.",
      "custom": {
        "module": [
          8
        ]
      }
    },
    {
      "id": "rebaudet2019cholera",
      "type": "article-journal",
      "author": [
        {
          "family": "Rebaudet",
          "given": "Stanislas"
        },
        {
          "family": "Sudre",
          "given": "Béatrice"
        },
        {
          "family": "Faucher",
          "given": "Benoît"
        },
        {
          "family": "Piarroux",
          "given": "Renaud"
        }
      ],
      "issued": {
        "date-parts": [
          [
            2019
          ]
        ]
      },
      "title": "Environmental determinants of cholera outbreaks in inland Africa: a systematic review of main drivers",
      "container-title": "Epidemiology and Infection",
      "volume": "147",
      "page": "e117",
      "DOI": "10.1017/S0950268819000074",
      "note": "Análise geoespacial de fatores ambientais que determinam surtos de cólera em locais sem acesso a água potável; contexto para entender persistência do surto no Haiti.",
      "custom": {
        "module": [
          8
        ]
      }
    },
    {
      "id": "cook2001prevention",
      "type": "article-journal",
      "author": [
        {
          "family": "Cook",
          "given": "Gordon C."
        }
      ],
      "issued": {
        "date-parts": [
          [
            2001
          ]
        ]
      },
      "title": "The prevention of cholera: a review of the work of John Snow and the contribution of sanitary engineers in the nineteenth century",
      "container-title": "History of Medicine Today",
      "volume": "12",
      "issue": "3",
      "page": "102–115",
      "note": "Análise comparativa de como Snow (epidemiologia) e Bazalgette (engenharia sanitária) atacaram o mesmo problema de ângulos complementares; uma com teoria correta, outra com ação estrutural.",
      "custom": {
        "module": [
          8
        ]
      }
    },
    {
      "id": "halliday2013great",
      "type": "book",
      "author": [
        {
          "family": "Halliday",
          "given": "Stephen"
        }
      ],
      "issued": {
        "date-parts": [
          [
            2013
          ]
        ]
      },
      "title": "The Great Filth: the War Against Bacteria and the Transformation of Everyday Life",
      "publisher": "Sutton Publishing",
      "publisher-place": "Stroud, Gloucestershire",
      "ISBN": "978-1845886509",
      "note": "História social e técnica do saneamento Vitoriano e sua luta contra doenças infecciosas, com foco especial em Londres e a motivação (política/social) por trás do investimento em infraestrutura.",
      "custom": {
        "module": [
          8
        ]
      }
    },
    {
      "id": "who2012sanitation",
      "type": "report",
      "author": [
        {
          "literal": "WHO and UNICEF"
        }
      ],
      "issued": {
        "date-parts": [
          [
            2012
          ]
        ]
      },
      "title": "Progress on Drinking-Water and Sanitation: 2012 Update",
      "publisher-place": "Geneva",
      "note": "Relatório global sobre custos e progresso na meta de acesso universal a saneamento; base para estimativas de investimento necessário.",
      "custom": {
        "module": [
          8
        ]
      }
    },
    {
      "id": "world_bank2015haiti",
      "type": "webpage",
      "author": [
        {
          "literal": "World Bank"
        }
      ],
      "issued": {
        "date-parts": [
          [
            2015
          ]
        ]
      },
      "title": "Haiti: Responds to Cholera",
      "note": "Case study do World Bank sobre resposta ao surto de 2010; inclui dados de financiamento, gap entre necessidade e alocação de recursos. — \\urlhttps://www.worldbank.org/en/results/2015/09/22/haiti-responds-to-cholera",
      "custom": {
        "module": [
          8
        ]
      }
    },
    {
      "id": "un2016secretarygeneral",
      "type": "webpage",
      "author": [
        {
          "literal": "United Nations"
        }
      ],
      "issued": {
        "date-parts": [
          [
            2016
          ]
        ]
      },
      "title": "Secretary-General Apologizes for United Nations' Role in Haiti Cholera Epidemic",
      "note": "Reconhecimento formal da responsabilidade da ONU na introdução da cólera no Haiti; inclui promessas de investimento ($400 milhões) posteriormente não cumpridas na magnitude prometida. — Press Release SG/SM/18323",
      "custom": {
        "module": [
          8
        ]
      }
    },
    {
      "id": "leavell1965preventive",
      "type": "book",
      "author": [
        {
          "family": "Leavell",
          "given": "Hugh Rodman"
        },
        {
          "family": "Clark",
          "given": "Edwin Gurney"
        }
      ],
      "issued": {
        "date-parts": [
          [
            1965
          ]
        ]
      },
      "title": "Preventive Medicine for the Doctor in His Community: An Epidemiologic Approach",
      "publisher": "McGraw-Hill",
      "publisher-place": "New York",
      "edition": "3",
      "note": "Texto-fonte do modelo clássico em três níveis de prevenção (primária, secundária, terciária), referência canônica que o conceito de prevenção quaternária viria a problematizar décadas depois."
    },
    {
      "id": "bentzen2003wonca",
      "type": "book",
      "editor": [
        {
          "family": "Bentzen",
          "given": "Niels"
        }
      ],
      "issued": {
        "date-parts": [
          [
            2003
          ]
        ]
      },
      "title": "Wonca Dictionary of General/Family Practice",
      "publisher": "Wonca International Classification Committee",
      "publisher-place": "Copenhagen",
      "note": "Dicionário oficial da Wonca (Organização Mundial dos Médicos de Família); registra a definição internacional de prevenção quaternária."
    },
    {
      "id": "jamoulle2015first",
      "type": "article-journal",
      "author": [
        {
          "family": "Jamoulle",
          "given": "Marc"
        }
      ],
      "issued": {
        "date-parts": [
          [
            2015
          ]
        ]
      },
      "title": "Quaternary Prevention: First, Do No Harm",
      "container-title": "Revista Brasileira de Medicina de Fam\\'ilia e Comunidade",
      "volume": "10",
      "issue": "35",
      "page": "1–3",
      "DOI": "10.5712/rbmfc10(35)1064",
      "note": "Editorial em revista brasileira que retoma o princípio hipocrático \"primum non nocere\" como fundamento da prevenção quaternária."
    },
    {
      "id": "illich1975medical",
      "type": "book",
      "author": [
        {
          "family": "Illich",
          "given": "Ivan"
        }
      ],
      "issued": {
        "date-parts": [
          [
            1975
          ]
        ]
      },
      "title": "Medical Nemesis: The Expropriation of Health",
      "publisher": "Calder and Boyars",
      "publisher-place": "London",
      "note": "Crítica radical da iatrogenia clínica, social e cultural; precursor conceitual da preocupação com o excesso de medicina que a prevenção quaternária viria a operacionalizar."
    },
    {
      "id": "moynihan2002selling",
      "type": "article-journal",
      "author": [
        {
          "family": "Moynihan",
          "given": "Ray"
        },
        {
          "family": "Heath",
          "given": "Iona"
        },
        {
          "family": "Henry",
          "given": "David"
        }
      ],
      "issued": {
        "date-parts": [
          [
            2002
          ]
        ]
      },
      "title": "Selling Sickness: The Pharmaceutical Industry and Disease Mongering",
      "container-title": "BMJ",
      "volume": "324",
      "issue": "7342",
      "page": "886–891",
      "DOI": "10.1136/bmj.324.7342.886",
      "note": "Marco do debate sobre disease mongering — a ampliação de fronteiras diagnósticas pela indústria farmacêutica e outros atores como vetor de medicalização."
    },
    {
      "id": "moynihan2002too",
      "type": "article-journal",
      "author": [
        {
          "family": "Moynihan",
          "given": "Ray"
        },
        {
          "family": "Smith",
          "given": "Richard"
        }
      ],
      "issued": {
        "date-parts": [
          [
            2002
          ]
        ]
      },
      "title": "Too Much Medicine? Almost Certainly",
      "container-title": "BMJ",
      "volume": "324",
      "issue": "7342",
      "page": "859–860",
      "DOI": "10.1136/bmj.324.7342.859",
      "note": "Editorial seminal sobre o \"excesso de medicina\" no BMJ; dialoga diretamente com a base conceitual da prevenção quaternária."
    },
    {
      "id": "welch2011overdiagnosed",
      "type": "book",
      "author": [
        {
          "family": "Welch",
          "given": "H. Gilbert"
        },
        {
          "family": "Schwartz",
          "given": "Lisa M."
        },
        {
          "family": "Woloshin",
          "given": "Steven"
        }
      ],
      "issued": {
        "date-parts": [
          [
            2011
          ]
        ]
      },
      "title": "Overdiagnosed: Making People Sick in the Pursuit of Health",
      "publisher": "Beacon Press",
      "publisher-place": "Boston",
      "ISBN": "9780807021996",
      "note": "Livro de divulgação que popularizou o debate sobre overdiagnosis: mostra como a busca por doenças em assintomáticos pode produzir rótulos, ansiedade e tratamentos sem necessariamente melhorar desfechos clínicos relevantes."
    },
    {
      "id": "sackett1996evidence",
      "type": "article-journal",
      "author": [
        {
          "family": "Sackett",
          "given": "David L."
        },
        {
          "family": "Rosenberg",
          "given": "William M. C."
        },
        {
          "family": "Gray",
          "given": "J. A. Muir"
        },
        {
          "family": "Haynes",
          "given": "R. Brian"
        },
        {
          "family": "Richardson",
          "given": "W. Scott"
        }
      ],
      "issued": {
        "date-parts": [
          [
            1996
          ]
        ]
      },
      "title": "Evidence Based Medicine: What It Is and What It Isn't",
      "container-title": "BMJ",
      "volume": "312",
      "issue": "7023",
      "page": "71–72",
      "DOI": "10.1136/bmj.312.7023.71",
      "note": "Definição clássica de medicina baseada em evidências como integração entre evidência científica, experiência clínica e valores do paciente."
    },
    {
      "id": "gervas2008clinical",
      "type": "article-journal",
      "author": [
        {
          "family": "G\\'ervas",
          "given": "Juan"
        },
        {
          "family": "Starfield",
          "given": "Barbara"
        },
        {
          "family": "Heath",
          "given": "Iona"
        }
      ],
      "issued": {
        "date-parts": [
          [
            2008
          ]
        ]
      },
      "title": "Is Clinical Prevention Better than Cure?",
      "container-title": "The Lancet",
      "volume": "372",
      "issue": "9654",
      "page": "1997–1999",
      "DOI": "10.1016/S0140-6736(08)61869-7",
      "note": "Análise dos limites da prevenção clínica; argumenta que rastreamentos e intervenções preventivas indiscriminadas podem causar mais dano do que benefício."
    },
    {
      "id": "rothman1976causes",
      "type": "article-journal",
      "author": [
        {
          "family": "Rothman",
          "given": "Kenneth J."
        }
      ],
      "issued": {
        "date-parts": [
          [
            1976
          ]
        ]
      },
      "title": "Causes",
      "container-title": "American Journal of Epidemiology",
      "volume": "104",
      "issue": "6",
      "page": "587–592",
      "DOI": "10.1093/oxfordjournals.aje.a112335",
      "note": "Formulação clássica do modelo de causas suficientes e componentes: define causa como qualquer fator cuja remoção preveniria a doença; introduz o conceito de \"torta causal\" (sufficient-cause model) e esclarece a distinção entre confundimento e modificação de efeito.",
      "custom": {
        "module": [
          2
        ]
      }
    },
    {
      "id": "rothman2005causation",
      "type": "article-journal",
      "author": [
        {
          "family": "Rothman",
          "given": "Kenneth J."
        },
        {
          "family": "Greenland",
          "given": "Sander"
        }
      ],
      "issued": {
        "date-parts": [
          [
            2005
          ]
        ]
      },
      "title": "Causation and Causal Inference in Epidemiology",
      "container-title": "American Journal of Public Health",
      "volume": "95",
      "issue": "S1",
      "page": "S144–S150",
      "DOI": "10.2105/AJPH.2004.059204",
      "note": "Revisão dos conceitos de causa e inferência causal em epidemiologia; desenvolve o modelo de causas suficientes e componentes, discute multicausalidade e interação, e argumenta que a inferência causal é melhor vista como mensuração de efeito do que como aplicação de critérios.",
      "custom": {
        "module": [
          2
        ]
      }
    },
    {
      "id": "cdc1990casedefs",
      "type": "article-journal",
      "author": [
        {
          "family": "Wharton",
          "given": "Melinda"
        },
        {
          "family": "Chorba",
          "given": "Terence L."
        },
        {
          "family": "Vogt",
          "given": "Richard L."
        },
        {
          "family": "Morse",
          "given": "Dale L."
        },
        {
          "family": "Buehler",
          "given": "James W."
        }
      ],
      "issued": {
        "date-parts": [
          [
            1990
          ]
        ]
      },
      "title": "Case Definitions for Public Health Surveillance",
      "container-title": "MMWR Recommendations and Reports",
      "volume": "39",
      "issue": "RR-13",
      "page": "1–43",
      "note": "Documento fundacional das definições padronizadas de caso para vigilância epidemiológica: define caso confirmado, caso provável e caso confirmado laboratorialmente, além de critérios clínicos, laboratoriais e epidemiológicos para mais de 50 doenças de notificação. Publicado pelos CDC em cooperação com o Council of State and Territorial Epidemiologists (CSTE).",
      "custom": {
        "module": [
          2
        ]
      }
    },
    {
      "id": "ms2022guia",
      "type": "book",
      "author": [
        {
          "literal": "Ministério da Saúde} and {Secretaria de Vigilância em Saúde"
        }
      ],
      "issued": {
        "date-parts": [
          [
            2022
          ]
        ]
      },
      "title": "Guia de Vigilância em Saúde",
      "publisher": "Ministério da Saúde",
      "publisher-place": "Brasília, DF",
      "edition": "5",
      "note": "Referência oficial do Ministério da Saúde para vigilância epidemiológica no Brasil: definições operacionais de caso (suspeito, provável, confirmado, descartado) por doença de notificação compulsória, critérios para encerramento no SINAN e condutas de controle. 5ª edição revisada e atualizada, 1128 p.",
      "custom": {
        "module": [
          2
        ]
      }
    },
    {
      "id": "fine2011herd",
      "type": "article-journal",
      "author": [
        {
          "family": "Fine",
          "given": "Paul"
        },
        {
          "family": "Eames",
          "given": "Ken"
        },
        {
          "family": "Heymann",
          "given": "David L."
        }
      ],
      "issued": {
        "date-parts": [
          [
            2011
          ]
        ]
      },
      "title": "“Herd Immunity”: A Rough Guide",
      "container-title": "Clinical Infectious Diseases",
      "volume": "52",
      "issue": "7",
      "page": "911–916",
      "DOI": "10.1093/cid/cir007",
      "note": "Revisão histórica, epidemiológica e teórica do conceito de imunidade de rebanho. Apresenta o limiar crítico de vacinação Vc = 1 − 1/R₀, discute populações heterogêneas, imunidade imperfeita, proteção indireta (herd effect) e implicações para políticas de vacinação.",
      "custom": {
        "module": [
          6
        ]
      }
    },
    {
      "id": "starfield2000us",
      "type": "article-journal",
      "author": [
        {
          "family": "Starfield",
          "given": "Barbara"
        }
      ],
      "issued": {
        "date-parts": [
          [
            2000
          ]
        ]
      },
      "title": "Is US Health Really the Best in the World?",
      "container-title": "JAMA",
      "volume": "284",
      "issue": "4",
      "page": "483–485",
      "DOI": "10.1001/jama.284.4.483",
      "note": "Análise comparativa do sistema de saúde americano expondo a magnitude dos danos iatrogênicos; argumento estrutural sobre segurança do paciente como dimensão central da qualidade assistencial."
    }
  ]
};
